import type { DesignerModel, DesignerNode, WorkflowVariable } from "../types";

export const MANUAL_ONBOARDING_TRIGGER_ID = "trig_manual";
export const MANUAL_ONBOARDING_TIMESTAMP_STEP_ID = "step_timestamp";
export const MANUAL_ONBOARDING_SET_VARIABLE_STEP_ID = "step_store_start_time";
export const MANUAL_ONBOARDING_NOTIFICATION_STEP_ID = "step_task_ping";
export const MANUAL_ONBOARDING_TIMESTAMP_FORMAT = "dddd, MMMM D [at] h:mm A";
export const MANUAL_ONBOARDING_SET_VARIABLE_NAME = "startedAt";
export const MANUAL_ONBOARDING_SET_VARIABLE_VALUE = "{{step_timestamp.formatted}}";
export const MANUAL_ONBOARDING_NOTIFICATION_TITLE = "{{workflow.notificationTitle}}";
export const MANUAL_ONBOARDING_NOTIFICATION_BODY =
  "{{workflow.taskOwner}}: {{workflow.taskName}}\nStarted at {{workflow.startedAt}}.";
export const MANUAL_ONBOARDING_NOTIFICATION_SEVERITY = "info";

const MANUAL_ONBOARDING_VARIABLES: WorkflowVariable[] = [
  {
    name: "startedAt",
    type: "string",
    scope: "workflow",
    defaultValue: "Set when the workflow runs",
    description: "Updated by Store Start Time using {{step_timestamp.formatted}}.",
    persistState: false,
  },
  {
    name: "notificationTitle",
    type: "string",
    scope: "workflow",
    defaultValue: "Task ping",
    description: "Used as the Send Notification title via {{workflow.notificationTitle}}.",
    persistState: false,
  },
  {
    name: "taskName",
    type: "string",
    scope: "workflow",
    defaultValue: "Review today's priority",
    description: "Used in the notification body via {{workflow.taskName}}.",
    persistState: false,
  },
  {
    name: "taskOwner",
    type: "string",
    scope: "workflow",
    defaultValue: "You",
    description: "Used in the notification body via {{workflow.taskOwner}}.",
    persistState: false,
  },
];

// A small but legitimately useful demo workflow we generate during the AI tour.
// It introduces workflow variables, {{workflow.var}} interpolation, and passing
// one step's output into another with {{step_id.field}}.
export function buildDemoWorkflow(id: string, name: string): DesignerModel {
  const triggerId = "trig_manual_demo";
  const step1 = "step_greet";
  const step2 = "step_timestamp";
  const step3 = "step_done";

  return {
    id,
    name,
    version: "1",
    description:
      "A small demo workflow generated by the onboarding tour. It uses workflow variables and passes one step's timestamp into the next step.",
    variables: [
      {
        name: "greeting",
        type: "string",
        scope: "workflow",
        defaultValue: "Hello there",
        description: "The greeting used in the first log step. Change it any time without editing the steps.",
        persistState: false,
      },
      {
        name: "task",
        type: "string",
        scope: "workflow",
        defaultValue: "review my inbox",
        description: "A short label for what this run is supposed to do.",
        persistState: false,
      },
    ],
    triggers: [
      {
        id: triggerId,
        type: "manual",
        label: "Run manually",
        args: {},
        position: { x: 120, y: 200 },
      },
    ],
    nodes: [
      {
        id: step1,
        type: "local.tool",
        tool: "log",
        label: "Greet",
        args: { message: "{{workflow.greeting}} - starting {{workflow.task}}." },
        fallbackTo: "",
        position: { x: 420, y: 200 },
      },
      {
        id: step2,
        type: "local.tool",
        tool: "get_datetime",
        label: "Get Timestamp",
        args: { format: MANUAL_ONBOARDING_TIMESTAMP_FORMAT },
        fallbackTo: "",
        position: { x: 720, y: 200 },
      },
      {
        id: step3,
        type: "local.tool",
        tool: "log",
        label: "Wrap up",
        args: { message: "Finished {{workflow.task}} at {{step_timestamp.formatted}}." },
        fallbackTo: "",
        position: { x: 1020, y: 200 },
      },
    ],
    wires: [
      { from: triggerId, to: step1 },
      { from: step1, to: step2 },
      { from: step2, to: step3 },
    ],
  };
}

export function buildManualOnboardingWorkflow(id: string, name: string): DesignerModel {
  return {
    id,
    name,
    version: "1",
    description:
      "A hands-on onboarding workflow that shows workflow variables and {{...}} data passing through a simple task notification.",
    variables: MANUAL_ONBOARDING_VARIABLES.map((variable) => ({ ...variable })),
    triggers: [
      {
        id: MANUAL_ONBOARDING_TRIGGER_ID,
        type: "manual",
        label: "Manual Trigger",
        args: {},
        position: { x: 120, y: 200 },
      },
    ],
    nodes: [
      {
        id: MANUAL_ONBOARDING_TIMESTAMP_STEP_ID,
        type: "local.tool",
        tool: "get_datetime",
        label: "Get Current Time",
        args: { format: MANUAL_ONBOARDING_TIMESTAMP_FORMAT },
        fallbackTo: "",
        position: { x: 460, y: 200 },
      },
      {
        id: MANUAL_ONBOARDING_SET_VARIABLE_STEP_ID,
        type: "local.tool",
        tool: "set_variable",
        label: "Store Start Time",
        args: {
          name: MANUAL_ONBOARDING_SET_VARIABLE_NAME,
          value: MANUAL_ONBOARDING_SET_VARIABLE_VALUE,
          scope: "workflow",
          type: "string",
          notifyUi: true,
        },
        fallbackTo: "",
        position: { x: 800, y: 200 },
      },
    ],
    wires: [],
  };
}

export function normalizeManualOnboardingWorkflow(model: DesignerModel): DesignerModel {
  let changed = false;

  const variablesByName = new Map<string, WorkflowVariable>();
  for (const variable of model.variables || []) {
    variablesByName.set(variable.name, variable);
  }
  for (const variable of MANUAL_ONBOARDING_VARIABLES) {
    const existing = variablesByName.get(variable.name);
    if (!existing) {
      variablesByName.set(variable.name, { ...variable });
      changed = true;
      continue;
    }

    const defaultValue =
      typeof existing.defaultValue === "string" && existing.defaultValue.trim()
        ? existing.defaultValue
        : variable.defaultValue;
    const normalized: WorkflowVariable = {
      ...existing,
      type: "string",
      scope: "workflow",
      defaultValue,
      description: existing.description || variable.description,
      persistState: false,
    };
    if (
      existing.type !== normalized.type
      || existing.scope !== normalized.scope
      || existing.defaultValue !== normalized.defaultValue
      || existing.description !== normalized.description
      || existing.persistState !== normalized.persistState
    ) {
      variablesByName.set(variable.name, normalized);
      changed = true;
    }
  }

  let nodes = model.nodes.map((node) => ({ ...node, args: cloneArgs(node.args) }));
  let wires = model.wires.map((wire) => ({ ...wire }));

  const renameNode = (fromId: string, toId: string) => {
    if (fromId === toId || nodes.some((node) => node.id === toId)) return fromId;
    nodes = nodes.map((node) => (node.id === fromId ? { ...node, id: toId } : node));
    wires = wires.map((wire) => ({
      ...wire,
      from: wire.from === fromId ? toId : wire.from,
      to: wire.to === fromId ? toId : wire.to,
    }));
    changed = true;
    return toId;
  };

  const timestamp = nodes.find((node) => node.id === MANUAL_ONBOARDING_TIMESTAMP_STEP_ID)
    || nodes.find((node) => node.tool === "get_datetime");
  if (timestamp) {
    const id = renameNode(timestamp.id, MANUAL_ONBOARDING_TIMESTAMP_STEP_ID);
    nodes = nodes.map((node) => {
      if (node.id !== id) return node;
      const next: DesignerNode = {
        ...node,
        label: "Get Current Time",
        args: { ...node.args, format: MANUAL_ONBOARDING_TIMESTAMP_FORMAT },
      };
      if (node.label !== next.label || node.args?.format !== next.args.format) changed = true;
      return next;
    });
  }

  const setVariable = nodes.find((node) => node.id === MANUAL_ONBOARDING_SET_VARIABLE_STEP_ID)
    || nodes.find((node) => node.tool === "set_variable");
  if (setVariable) {
    const id = renameNode(setVariable.id, MANUAL_ONBOARDING_SET_VARIABLE_STEP_ID);
    nodes = nodes.map((node) => {
      if (node.id !== id) return node;
      const nextArgs = {
        ...node.args,
        name: MANUAL_ONBOARDING_SET_VARIABLE_NAME,
        value: MANUAL_ONBOARDING_SET_VARIABLE_VALUE,
        scope: "workflow",
        type: "string",
        notifyUi: true,
      };
      const next: DesignerNode = {
        ...node,
        label: "Store Start Time",
        args: nextArgs,
      };
      if (
        node.label !== next.label
        || node.args?.name !== nextArgs.name
        || node.args?.value !== nextArgs.value
        || node.args?.scope !== nextArgs.scope
        || node.args?.type !== nextArgs.type
        || node.args?.notifyUi !== nextArgs.notifyUi
      ) {
        changed = true;
      }
      return next;
    });
  }

  const notification = nodes.find((node) => node.id === MANUAL_ONBOARDING_NOTIFICATION_STEP_ID)
    || nodes.find((node) => node.tool === "send_notification");
  if (notification) {
    const id = renameNode(notification.id, MANUAL_ONBOARDING_NOTIFICATION_STEP_ID);
    nodes = nodes.map((node) => {
      if (node.id !== id) return node;
      const nextArgs = {
        ...node.args,
        title: MANUAL_ONBOARDING_NOTIFICATION_TITLE,
        body: MANUAL_ONBOARDING_NOTIFICATION_BODY,
        severity: MANUAL_ONBOARDING_NOTIFICATION_SEVERITY,
      };
      const next: DesignerNode = {
        ...node,
        label: "Send Task Ping",
        args: nextArgs,
      };
      if (
        node.label !== next.label
        || node.args?.title !== nextArgs.title
        || node.args?.body !== nextArgs.body
        || node.args?.severity !== nextArgs.severity
      ) {
        changed = true;
      }
      return next;
    });
  }

  if (!changed) return model;
  return { ...model, variables: Array.from(variablesByName.values()), nodes, wires };
}

export function getManualOnboardingValidation(model: DesignerModel | null | undefined) {
  const variables = model?.variables || [];
  const findVariable = (name: string) => variables.find((variable) => variable.name === name);
  const variableNames = MANUAL_ONBOARDING_VARIABLES.map((variable) => variable.name);
  const variablesReady = variableNames.every((name) => {
    const variable = findVariable(name);
    return Boolean(
      variable
      && variable.type === "string"
      && (variable.scope || "workflow") === "workflow"
      && typeof variable.defaultValue === "string"
      && variable.defaultValue.trim().length > 0
    );
  });

  const timestampNode = model?.nodes?.find((node) => node.id === MANUAL_ONBOARDING_TIMESTAMP_STEP_ID);
  const timestampReady = Boolean(
    timestampNode
    && timestampNode.tool === "get_datetime"
    && timestampNode.args?.format === MANUAL_ONBOARDING_TIMESTAMP_FORMAT
  );

  const setVariableNode = model?.nodes?.find((node) => node.id === MANUAL_ONBOARDING_SET_VARIABLE_STEP_ID);
  const setVariableReady = Boolean(
    setVariableNode
    && setVariableNode.tool === "set_variable"
    && setVariableNode.args?.name === MANUAL_ONBOARDING_SET_VARIABLE_NAME
    && setVariableNode.args?.value === MANUAL_ONBOARDING_SET_VARIABLE_VALUE
    && setVariableNode.args?.scope === "workflow"
    && setVariableNode.args?.type === "string"
    && setVariableNode.args?.notifyUi === true
  );

  const notificationNode = model?.nodes?.find((node) => node.id === MANUAL_ONBOARDING_NOTIFICATION_STEP_ID);
  const notificationNodeExists = Boolean(notificationNode);
  const notificationArgsReady = Boolean(
    notificationNode
    && notificationNode.tool === "send_notification"
    && notificationNode.args?.title === MANUAL_ONBOARDING_NOTIFICATION_TITLE
    && notificationNode.args?.body === MANUAL_ONBOARDING_NOTIFICATION_BODY
    && notificationNode.args?.severity === MANUAL_ONBOARDING_NOTIFICATION_SEVERITY
  );

  const triggerWireReady = Boolean(model?.wires?.some(
    (wire) =>
      wire.from === MANUAL_ONBOARDING_TRIGGER_ID
      && wire.to === MANUAL_ONBOARDING_TIMESTAMP_STEP_ID
  ));

  const notificationWireReady = Boolean(model?.wires?.some(
    (wire) =>
      wire.from === MANUAL_ONBOARDING_SET_VARIABLE_STEP_ID
      && wire.to === MANUAL_ONBOARDING_NOTIFICATION_STEP_ID
  ));

  const storeVariableWireReady = Boolean(model?.wires?.some(
    (wire) =>
      wire.from === MANUAL_ONBOARDING_TIMESTAMP_STEP_ID
      && wire.to === MANUAL_ONBOARDING_SET_VARIABLE_STEP_ID
  ));

  return {
    variablesReady,
    timestampReady,
    setVariableReady,
    notificationNodeExists,
    notificationArgsReady,
    triggerWireReady,
    storeVariableWireReady,
    notificationWireReady,
    readyToRun:
      variablesReady
      && timestampReady
      && setVariableReady
      && notificationArgsReady
      && triggerWireReady
      && storeVariableWireReady
      && notificationWireReady,
  };
}

function cloneArgs(args: any) {
  if (!args || typeof args !== "object") return {};
  try {
    return JSON.parse(JSON.stringify(args));
  } catch {
    return { ...args };
  }
}

interface FakeMessage {
  role: "user" | "assistant" | "system";
  content: string;
}

interface ChatLike {
  setMessages: (updater: (prev: any[]) => any[]) => void;
  setBusy: (busy: boolean) => void;
}

interface RunAiDemoSequenceArgs {
  chat: ChatLike;
  applyModel: (model: DesignerModel) => void;
  workflowId: string;
  workflowName: string;
  onApplied?: () => void;
}

// The full narration is delivered as a series of short assistant messages,
// each landing on a delay so the user reads the build like a story rather than
// a wall of text. The model gets applied right after the planning beat so the
// canvas materializes mid-explanation, the same rhythm a real AI build has.
const NARRATION_BEATS: Array<{
  delayMs: number;
  role: "user" | "assistant";
  content: string;
  applyModelHere?: boolean;
}> = [
  {
    delayMs: 0,
    role: "user",
    content:
      "Build me a small starter workflow I can run on demand. I'd like to see how variables and {{ }} references work too.",
  },
  {
    delayMs: 60,
    role: "assistant",
    content:
      "Got it. I'll make a small one you can actually keep:\n\n" +
      "1. Manual trigger so you decide when it runs.\n" +
      "2. Two workflow variables, greeting and task, so the text is easy to change.\n" +
      "3. A timestamp step whose output gets passed forward with {{step_timestamp.formatted}}.\n\n" +
      "Designing it now...",
  },
  {
    delayMs: 1700,
    role: "assistant",
    content:
      "Trigger, variables, and steps are in place. Wiring the timestamp into the final log now.",
    applyModelHere: true,
  },
  {
    delayMs: 2600,
    role: "assistant",
    content:
      "Quick note on {{ }}: anything inside those braces is filled in when the workflow runs. {{workflow.task}} reads a workflow variable; {{step_timestamp.formatted}} reads the formatted output from the timestamp step.",
  },
  {
    delayMs: 3500,
    role: "assistant",
    content:
      "Done. The coach will walk you through Variables, Save, Run, Logs, and Docs so you can see the substituted values in a real run.",
  },
];

// Drive the narrated demo. Returns a cleanup function the caller can use to
// abort if the user skips out mid-sequence.
export function runAiDemoSequence({
  chat,
  applyModel,
  workflowId,
  workflowName,
  onApplied,
}: RunAiDemoSequenceArgs): () => void {
  const timers: number[] = [];
  let aborted = false;

  chat.setBusy(true);

  const append = (msg: FakeMessage) => {
    chat.setMessages((prev: FakeMessage[]) => [...prev, { ...msg } as FakeMessage]);
  };

  for (const beat of NARRATION_BEATS) {
    const t = window.setTimeout(() => {
      if (aborted) return;
      append({ role: beat.role, content: beat.content });
      if (beat.applyModelHere) {
        const demo = buildDemoWorkflow(workflowId, workflowName);
        applyModel(demo);
        onApplied?.();
      }
    }, beat.delayMs);
    timers.push(t);
  }

  const tDone = window.setTimeout(() => {
    if (aborted) return;
    chat.setBusy(false);
  }, NARRATION_BEATS[NARRATION_BEATS.length - 1].delayMs + 600);
  timers.push(tDone);

  return () => {
    aborted = true;
    for (const t of timers) window.clearTimeout(t);
    chat.setBusy(false);
  };
}
