
import React from 'react';
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Terms of Use',
  description: 'Terms of Use for Stuard AI services.',
};

export default function TermsPage() {
  return (
    <div className="max-w-4xl mx-auto px-6 py-12 md:py-20">
      <h1 className="text-4xl md:text-5xl font-serif font-medium mb-8">Terms of Use</h1>
      <p className="text-gray-600 mb-12">Last updated: December 24, 2025</p>

      <div className="prose prose-lg prose-gray max-w-none space-y-12">
        <section>
          <h2 className="text-2xl font-medium text-gray-900 mb-4">1. Acceptance of Terms</h2>
          <p>
            By accessing or using Stuard AI ("the Service"), you agree to be bound by these Terms of Use. 
            If you do not agree to these terms, please do not use the Service.
          </p>
        </section>

        <section>
          <h2 className="text-2xl font-medium text-gray-900 mb-4">2. Description of Service</h2>
          <p>
            Stuard AI is a desktop assistant application designed to help with computer tasks through automation and AI interaction. 
            The Service includes a desktop application that runs locally on your device and cloud-based services for synchronization, 
            AI processing, and marketplace features.
          </p>
        </section>

        <section>
          <h2 className="text-2xl font-medium text-gray-900 mb-4">3. Beta Access</h2>
          <p>
            The Service is currently in a Beta phase. You acknowledge that the Service may contain bugs, errors, and other problems 
            that could cause system or other failures and data loss. We may modify or discontinue features at any time without notice. 
            Beta access may be limited to specific users or groups ("stable", "beta", "staging").
          </p>
        </section>

        <section>
          <h2 className="text-2xl font-medium text-gray-900 mb-4">4. User Accounts and Security</h2>
          <p>
            You are responsible for maintaining the confidentiality of your account credentials and for all activities that occur under your account. 
            You agree to notify us immediately of any unauthorized use of your account.
          </p>
        </section>

        <section>
          <h2 className="text-2xl font-medium text-gray-900 mb-4">5. Local-First Data and Privacy</h2>
          <p>
            Stuard AI is designed with a "local-first" philosophy. Much of your data, including local memory and task history, is stored locally on your device. 
            However, certain features require data to be processed in the cloud (e.g., AI model inference, syncing across devices, marketplace publishing). 
            By using these features, you consent to such processing as described in our Privacy Policy.
          </p>
        </section>

        <section>
          <h2 className="text-2xl font-medium text-gray-900 mb-4">6. Marketplace and User Content</h2>
          <p>
            Users may publish workflows, automations, or other content ("User Content") to the Stuard Marketplace.
          </p>
          <ul className="list-disc pl-6 space-y-2 mt-4">
            <li><strong>Ownership:</strong> You retain ownership of your User Content.</li>
            <li><strong>License:</strong> By publishing User Content, you grant Stuard AI and other users a license to use, copy, modify, and execute your workflows.</li>
            <li><strong>Responsibility:</strong> You are solely responsible for User Content you publish. You must not publish content that is illegal, malicious, or violates the rights of others.</li>
          </ul>
        </section>

        <section>
          <h2 className="text-2xl font-medium text-gray-900 mb-4">7. Acceptable Use</h2>
          <p>
            You agree not to use the Service to:
          </p>
          <ul className="list-disc pl-6 space-y-2 mt-4">
            <li>Violate any laws or regulations.</li>
            <li>Infringe upon the intellectual property rights of others.</li>
            <li>Distribute malware or malicious workflows.</li>
            <li>Interfere with or disrupt the integrity or performance of the Service.</li>
            <li>Attempt to gain unauthorized access to the Service or related systems.</li>
          </ul>
        </section>

        <section>
          <h2 className="text-2xl font-medium text-gray-900 mb-4">8. AI Limitations</h2>
          <p>
            The Service utilizes Artificial Intelligence technologies. You acknowledge that:
          </p>
          <ul className="list-disc pl-6 space-y-2 mt-4">
            <li>AI outputs may be inaccurate, offensive, or biased.</li>
            <li>You should verify any information or code generated by the Service before relying on it.</li>
            <li>We are not responsible for any actions taken based on AI-generated advice or automations.</li>
          </ul>
        </section>

        <section>
          <h2 className="text-2xl font-medium text-gray-900 mb-4">9. Third-Party Services</h2>
          <p>
            The Service may integrate with third-party applications (e.g., Google, GitHub, Outlook). Use of these integrations is subject 
            to the terms and policies of those third parties. Stuard AI is not responsible for the availability or accuracy of third-party services.
          </p>
        </section>

        <section>
          <h2 className="text-2xl font-medium text-gray-900 mb-4">10. Disclaimer of Warranties</h2>
          <p>
            THE SERVICE IS PROVIDED "AS IS" AND "AS AVAILABLE" WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED, 
            INCLUDING, BUT NOT LIMITED TO, IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT.
          </p>
        </section>

        <section>
          <h2 className="text-2xl font-medium text-gray-900 mb-4">11. Limitation of Liability</h2>
          <p>
            IN NO EVENT SHALL STUARD AI BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL OR PUNITIVE DAMAGES, 
            INCLUDING WITHOUT LIMITATION, LOSS OF PROFITS, DATA, USE, GOODWILL, OR OTHER INTANGIBLE LOSSES, RESULTING FROM 
            YOUR ACCESS TO OR USE OF OR INABILITY TO ACCESS OR USE THE SERVICE.
          </p>
        </section>

        <section>
          <h2 className="text-2xl font-medium text-gray-900 mb-4">12. Changes to Terms</h2>
          <p>
            We reserve the right to modify these Terms at any time. We will provide notice of significant changes. 
            Your continued use of the Service after such changes constitutes your acceptance of the new Terms.
          </p>
        </section>

        <section>
          <h2 className="text-2xl font-medium text-gray-900 mb-4">13. Contact Us</h2>
          <p>
            If you have any questions about these Terms, please contact us at support@stuard.ai.
          </p>
        </section>
      </div>
    </div>
  );
}
